micronaut:
  application:
    name: http2error

  server:
    cors:
      enabled: true

logger:
  levels:
    io.micronaut.context: WARN
    io.micronaut.core.reflect: WARN

endpoints:
  health:
    details-visible: ANONYMOUS
